-- Database export: ohyesainext
-- Date: 2026-07-01 13:46:06
-- Generated by DBX

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `user_oauth_bind` (
  `id` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `user_id` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `platform` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '平台: WX ',
  `openid` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `unionid` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `create_time` datetime NOT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `user_id` (`openid`,`platform`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='用户三方oahtu登录信息绑定表';

CREATE TABLE `user_tracking` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `referer` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '来源；从那个网站跳过来的',
  `target` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '目标，访问的是哪个功能点',
  `from_ip` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `platform` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '平台来源',
  `create_time` datetime NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=90386 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE `vio_project` (
  `id` char(32) NOT NULL COMMENT 'md5(file id)',
  `user_id` char(32) NOT NULL,
  `session_id` char(32) NOT NULL,
  `message_id` char(32) NOT NULL,
  `project_name` varchar(200) DEFAULT NULL,
  `args` json NOT NULL COMMENT '生成参数',
  `file_id` varchar(500) NOT NULL COMMENT '生成结果',
  `preview_file_id` varchar(500) DEFAULT NULL COMMENT '预览文件id，通常代表封面',
  `media_duration` int DEFAULT NULL COMMENT '媒体类型文件时长',
  `lyrics` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '音频文件歌词',
  `task_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '任务类型',
  `show_project` tinyint NOT NULL COMMENT '是否展示项目',
  `model_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '使用的模型名称',
  `create_time` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `file_id` (`file_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `points_transaction_log` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` char(32) NOT NULL,
  `transaction_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '交易类型：RECHARGE(充值), DEDUCT(扣减), SYSTEM_GRANT(系统赠送)',
  `amount` int NOT NULL COMMENT '变动数量 (正数或负数)',
  `balance_after` int NOT NULL COMMENT '变动后的余额',
  `description` varchar(255) DEFAULT NULL COMMENT '描述 (如：开通基础版月卡，或 调用Mureka O2生成音乐)',
  `create_time` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=24712 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='积分变动流水表';

CREATE TABLE `model_pricing_rule` (
  `id` int NOT NULL AUTO_INCREMENT,
  `task_type` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '任务类型 (e.g., 音乐生成, 故事类MV-15秒)',
  `model_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '调用模型 (e.g., Mureka O2, viduq2)',
  `resolution` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '分辨率；',
  `points_required` int NOT NULL COMMENT '消耗积分 (e.g., 5, 4, 14, 65)',
  `is_active` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否启用',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_task_model` (`task_type`,`model_name`,`resolution`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='模型调用计费规则表';

CREATE TABLE `invitation_records` (
  `id` int NOT NULL AUTO_INCREMENT,
  `inviter_id` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '邀请人id',
  `invitee_id` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '受邀人id',
  `invite_code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '使用的邀请码',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=2123603971 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='邀请记录表';

CREATE TABLE `pay_order` (
  `id` char(32) NOT NULL,
  `user_id` char(32) NOT NULL,
  `trade_no` char(32) NOT NULL COMMENT '订单号',
  `tier_code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '订阅计划code',
  `state` int NOT NULL COMMENT '订单状态',
  `amount` int NOT NULL COMMENT '总额/分',
  `create_time` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `trade_no` (`trade_no`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='主要作用是持久化用户的交易信息，防止系统出现意外无法找回';

CREATE TABLE `session_points_transaction_map` (
  `id` int NOT NULL AUTO_INCREMENT,
  `chat_session_id` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '对话session id',
  `points_transaction_log_id` int NOT NULL COMMENT '订单流水id points_transaction_log_id',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `chat_session_id` (`chat_session_id`,`points_transaction_log_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=17352 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='映射对话产生的所有积分消费信息';

CREATE TABLE `history_message_chunk` (
  `id` int NOT NULL AUTO_INCREMENT,
  `history_message_id` char(32) NOT NULL,
  `chat_session_task_id` int DEFAULT NULL COMMENT '对应的任务表单数据；',
  `chunk` json NOT NULL,
  PRIMARY KEY (`id`),
  KEY `history_message_id` (`history_message_id`)
) ENGINE=InnoDB AUTO_INCREMENT=6501147 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='同一个 history_message_id  下的所有记录代表一次完整的回复';

CREATE TABLE `user_points_batch` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '用户ID',
  `points_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '积分类型：RECHARGE(充值), REGISTER（注册赠送）, INVITE（邀请赠送）',
  `total_amount` int NOT NULL COMMENT '获取的总积分数',
  `remaining_amount` int NOT NULL COMMENT '当前剩余可用积分数',
  `expire_time` datetime NOT NULL COMMENT '过期时间 (永不过期为超大时间 2126-05-25 00:00:00 )',
  `create_time` datetime NOT NULL COMMENT '获取时间',
  `update_time` datetime NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `user_id` (`user_id`,`expire_time`,`remaining_amount`) USING BTREE COMMENT '查询用户有效的剩余积分'
) ENGINE=InnoDB AUTO_INCREMENT=6273 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='用户积分包明细表 (控制过期与扣减顺序)';

CREATE TABLE `subscription_plan` (
  `id` int NOT NULL AUTO_INCREMENT,
  `tier_code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '套餐编码\n\n免费版  FREE\n基础版  BASIC\n标准版  STANDARD  \n专业版  PRO\n',
  `tier_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '套餐名称 (e.g., 基础版, 标准版)',
  `tier_level` int NOT NULL COMMENT '套餐等级',
  `price` int NOT NULL COMMENT '价格/分',
  `subscription_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '订阅类型  年付：YEAR,  月付：MONTH,  积分包: POINT_PKG',
  `granted_points` int NOT NULL COMMENT '赠送/包含积分数 (e.g., 780, 1800)',
  `description` json DEFAULT NULL COMMENT '订阅描述',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `tier_code` (`tier_code`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='会员套餐规则表';

CREATE TABLE `chat_session` (
  `id` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `user_id` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '对话名称',
  `metadata` json DEFAULT NULL COMMENT '元数据，json格式',
  `update_time` datetime NOT NULL COMMENT '更新日期',
  `create_time` datetime NOT NULL COMMENT '创建日期',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `user_id` (`user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='对话表';

CREATE TABLE `history_message` (
  `id` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `chat_session_id` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'chat_session_id',
  `content` json DEFAULT NULL COMMENT '对话内容',
  `seq_no` int NOT NULL AUTO_INCREMENT COMMENT '序号; 自动递增',
  `sender_type` int NOT NULL COMMENT '1: user; 2 model;',
  `like_state` tinyint NOT NULL COMMENT '0 未点赞；1 点赞； 2 点踩；',
  `finish` tinyint NOT NULL COMMENT '标识本消息是否回复完毕 ;0未完成；1完成',
  `create_time` datetime NOT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `seq_no` (`seq_no`) USING BTREE,
  KEY `chat_session_id` (`chat_session_id`,`seq_no`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=63609 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='历史对话消息表，存储全量对话记录\n每条记录代表一条消息，一条消息又由 n 条 chunk 构成';

CREATE TABLE `chat_session_task` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT 'session下的task_id',
  `chat_session_id` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'chat session id',
  `payload` json DEFAULT NULL COMMENT '任务的json数据',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `chat_session_id` (`chat_session_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1987 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='chat session 对话下的任务数据，一个session下用户可能开启多个任务；为了减小模型的负担 任务数据通过数据库维护   模型只负责传入taskid 与 增量数据';

CREATE TABLE `memory_message` (
  `id` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `session_id` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'chat_session_id;  有时候此id为临时id 所以不会再chat session表出现',
  `content` json DEFAULT NULL COMMENT '对话内容',
  `seq_no` int NOT NULL COMMENT '序号',
  `create_time` datetime NOT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `session_id` (`session_id`,`seq_no`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='模型当前对话的持久化记忆，由框架操作存储; 注意区分记忆与历史的概念，历史是展示在聊天窗口的数据，可能很长，记忆是每次传给模型的message array 通常长度是有限制的';

CREATE TABLE `user` (
  `id` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `account` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '账号',
  `mobile` varchar(11) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '手机号',
  `password` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '密码摘要',
  `nick_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '昵称',
  `gender` int DEFAULT NULL COMMENT '性别：0 男；1 女；',
  `birth_date` datetime DEFAULT NULL COMMENT '出生日期',
  `avatar_img` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '头像',
  `points_balance` int DEFAULT NULL COMMENT '积分余额',
  `subscription_plan_tier_code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '用户订阅计划',
  `subscription_end_time` datetime DEFAULT NULL COMMENT '用户订阅到期时间',
  `api_key` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'api密钥',
  `invite_code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '用户专属邀请码',
  `create_time` datetime NOT NULL COMMENT '创建日期',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `account_source` (`account`) USING BTREE,
  UNIQUE KEY `mobile` (`mobile`) USING BTREE,
  UNIQUE KEY `api_key` (`api_key`) USING BTREE,
  UNIQUE KEY `invite_code` (`invite_code`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE `share_vio_project` (
  `id` int NOT NULL AUTO_INCREMENT,
  `vio_project_id` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=74 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `points_grant_schedule` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` char(32) NOT NULL,
  `trade_no` varchar(64) NOT NULL COMMENT '关联的年费充值订单号; payOrder 表字段',
  `tier_code` varchar(20) NOT NULL COMMENT '关联的订阅计划code',
  `period_index` int NOT NULL COMMENT '期数 (例如：1到12)',
  `points_to_grant` int NOT NULL COMMENT '本期应发积分数量',
  `expected_grant_date` datetime NOT NULL COMMENT '预计发放日期 (如: 2026-03-15)',
  `status` varchar(32) NOT NULL DEFAULT 'PENDING' COMMENT '状态: PENDING(待发放), GRANTED(已发放)',
  `actual_grant_time` datetime DEFAULT NULL COMMENT '实际发放成功的时间',
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_status_date` (`status`,`expected_grant_date`)
) ENGINE=InnoDB AUTO_INCREMENT=61 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='包年套餐按月积分发放计划表';

CREATE TABLE `user_feedback` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `message_id` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `attitude_type` int NOT NULL COMMENT '1 满意；2 不满意',
  `content` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '反馈内容',
  `create_time` datetime NOT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `message_id` (`message_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=590 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='用户反馈表';

SET FOREIGN_KEY_CHECKS = 1;
