spring:
  datasource:
    username: 
    password: 
    url: jdbc:mysql://10.8.0.4:3306/ohyesainext?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
#    username: root
#    password: root
#    url: jdbc:mysql://127.0.0.1:3306/ohyesainext?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true

##################### tos ###########################################
tos:
  bucket: ohyesainext-test

######################### model api ######################
model-api:
  # 自己的 new api
  guoyan:
    ak: 


#################### mv-audio-analyzer ################################
mv-analyzer:
  base-url: http://10.8.0.4:8000